/det/material silicon
/run/initialize

/gun/particle alpha
/run/printProgress 2000

/gun/energy 4 MeV
/io/output ../results/bragg_si_4MeV
/run/beamOn 5000

/gun/energy 5 MeV
/io/output ../results/bragg_si_5MeV
/run/beamOn 5000

/gun/energy 6 MeV
/io/output ../results/bragg_si_6MeV
/run/beamOn 5000

/gun/energy 7 MeV
/io/output ../results/bragg_si_7MeV
/run/beamOn 5000

/gun/energy 8 MeV
/io/output ../results/bragg_si_8MeV
/run/beamOn 5000
